project 'Pisth APT.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pisth APT' do

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pisth APT
  pod "NMSSH"
  pod "BiometricAuthentication", "~> 2.1"
  pod "Google-Mobile-Ads-SDK"
  pod "Firebase/Core"
end
